### ISSUE TITLE
setTheme [THEME]

### ISSUE THREAD

**Issue by trollbreeder** [oxygencraft/DebugMod#6]
Sets theme to one of the included themes.

Blue
Purple (LE)
Green
CSEC/White
Mint
Yellow

There is ***NO*** support for dlc themes, as they are setCustomTheme.

**Comment by oxygencraft** [comment]
Added Command

Usage: setTheme (Theme)
Valid Options: TerminalOnly,Blue,Teal,Yellow,Green,White,Purple,Mint,Colamaeleon,GreenCompact,Riptide,Riptide2
